### ISSUE TITLE
安装cupy后运行产生报错

### ISSUE THREAD

**Issue by star-123456** [fangwei123456/spikingjelly#126]
在运行dvs128时，使用如下启动方式：python -m spikingjelly.clock_driven.examples.classify_dvsg -data_dir /home/yangdayou/datasets/DVS128Gesture -out_dir ./logs -amp -opt Adam -device cuda:0 -lr_scheduler CosALR -T_max 64 -cupy -epochs 1024，产生报错
Traceback (most recent call last):
  File "/home/yangdayou/anaconda3/envs/pytorch/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/yangdayou/anaconda3/envs/pytorch/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/yangdayou/anaconda3/envs/pytorch/lib/python3.8/site-packages/spikingjelly/clock_driven/examples/classify_dvsg.py", line 428, in <module>
    main()
  File "/home/yangdayou/anaconda3/envs/pytorch/lib/python3.8/site-packages/spikingjelly/clock_driven/examples/classify_dvsg.py", line 361, in main
    out_fr = net(frame)
  File "/home/yangdayou/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/yangdayou/anaconda3/envs/pytorch/lib/python3.8/site-packages/spikingjelly/clock_driven/examples/classify_dvsg.py", line 91, in forward
    out_spikes = self.fc(self.conv(x))  # shape = [T, N, 110]
  File "/home/yangdayou/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/yangdayou/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/home/yangdayou/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/yangdayou/anaconda3/envs/pytorch/lib/python3.8/site-packages/spikingjelly/clock_driven/neuron.py", line 528, in forward
    self.spike_seq, self.v_seq = neuron_kernel.MultiStepLIFNodePTT.apply(
  File "/home/yangdayou/anaconda3/envs/pytorch/lib/python3.8/site-packages/spikingjelly/clock_driven/neuron_kernel.py", line 630, in forward
    cp_dtype = cupy.float16
AttributeError: module 'cupy' has no attribute 'float16'
请问这个报错应该如何解决？

**Comment by Yanqi-Chen** [comment]
试一下直接执行这个
```python
import cupy
print(cupy.float16)
```

**Comment by star-123456** [comment]
> ```python
> print(cupy.float16)
> ```

执行了，显示没有这个module，但我不知道怎么添加，报错如下：
>>> import cupy
>>> print(cupy.float16)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'cupy' has no attribute 'float16'

**Comment by Yanqi-Chen** [comment]
conda list看一下cupy安装的版本

**Comment by star-123456** [comment]
> conda list看一下cupy安装的版本

cupy 9.4.0版本

**Comment by Yanqi-Chen** [comment]
> > conda list看一下cupy安装的版本
> 
> cupy 9.4.0版本

python版本需要>=3.7才可以直接通过`cupy.<类型>`获得类型，低于这个版本应该直接用`numpy.<类型>`，见

https://github.com/cupy/cupy/blob/58f3db25304155b3966af662de42315a714c612e/cupy/__init__.py#L863-L889

@fangwei123456 ，这里需要判断python版本

**Comment by star-123456** [comment]
> > > conda list看一下cupy安装的版本
> > 
> > 
> > cupy 9.4.0版本
> 
> python版本需要>=3.7才可以直接通过`cupy.<类型>`获得类型，低于这个版本应该直接用`numpy.<类型>`，见
> 
> https://github.com/cupy/cupy/blob/58f3db25304155b3966af662de42315a714c612e/cupy/__init__.py#L863-L889
> 
> @fangwei123456 ，这里需要判断python版本

非常感谢，我在进行试验的时候也有一个猜想，可能跟使用的服务器是集显有关，与cupy版本不匹配也有关系，重新安装9.4.0版本后可以进行加速，但batch size=32时仍然爆掉了显存，目前问题基本解决。

**Comment by star-123456** [comment]
> > > conda list看一下cupy安装的版本
> > 
> > 
> > cupy 9.4.0版本
> 
> python版本需要>=3.7才可以直接通过`cupy.<类型>`获得类型，低于这个版本应该直接用`numpy.<类型>`，见
> 
> https://github.com/cupy/cupy/blob/58f3db25304155b3966af662de42315a714c612e/cupy/__init__.py#L863-L889
> 
> @fangwei123456 ，这里需要判断python版本

为什么重新安装同版本后可以加速我也不太清楚，可能是上一次安装时本身出现一些问题

**Comment by Yanqi-Chen** [comment]
> > > > conda list看一下cupy安装的版本
> > > 
> > > 
> > > cupy 9.4.0版本
> > 
> > 
> > python版本需要>=3.7才可以直接通过`cupy.<类型>`获得类型，低于这个版本应该直接用`numpy.<类型>`，见
> > https://github.com/cupy/cupy/blob/58f3db25304155b3966af662de42315a714c612e/cupy/__init__.py#L863-L889
> > @fangwei123456 ，这里需要判断python版本
> 
> 为什么重新安装同版本后可以加速我也不太清楚，可能是上一次安装时本身出现一些问题

OK现在应该没有问题了，显存不够只能减batchsize了
