### ISSUE TITLE
Error in SpikingHeidelbergDigits dataloader

### ISSUE THREAD

**Issue by negishubham** [fangwei123456/spikingjelly#300]
Hi, 

I am getting below error when I am trying to use SpikingHeidelbergDigits dataloader. The code that I am using for the dataloader is also given below. I see that self.length is not defined for data_type='frame' but not sure if I can define it myself or if I will edit it correctly or not. 

I have another question that is related to SpikingHeidelbergDigitsdataset. So as far as I know this dataset has recordings ranging from 0.24s to 1.17s so how long recordings do you take? Because we would use batching and we would like all recordings to be of the same length in the batch. Is there a parameter in the dataloader that I can set to set the length for the recordings? 

############# My Code
train_set = shd.SpikingHeidelbergDigits(root=args.data_path, data_type='frame', frames_number=args.timesteps, split_by='number', train=True)
test_set = shd.SpikingHeidelbergDigits(root=args.data_path, data_type='frame', frames_number=args.timesteps, split_by='number', train=False)
train_loader = torch.utils.data.DataLoader(train_set, batch_size=args.batch_size, shuffle=True, num_workers=args.workers, pin_memory=True)
test_loader = torch.utils.data.DataLoader(test_set, batch_size=args.val_batch_size, shuffle=False,num_workers=args.workers, pin_memory=True)

#############  ERROR
Traceback (most recent call last):
    train_loader = torch.utils.data.DataLoader(train_set, batch_size=args.batch_size, shuffle=True, num_workers=args.workers, pin_memory=True)
  File "/anaconda3/envs/pt17/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 353, in __init__
    sampler = RandomSampler(dataset, generator=generator)  # type: ignore[arg-type]
  File "/anaconda3/envs/pt17/lib/python3.9/site-packages/torch/utils/data/sampler.py", line 106, in __init__
    if not isinstance(self.num_samples, int) or self.num_samples <= 0:
  File "/anaconda3/envs/pt17/lib/python3.9/site-packages/torch/utils/data/sampler.py", line 114, in num_samples
    return len(self.data_source)
  File "/anaconda3/envs/pt17/lib/python3.9/site-packages/spikingjelly-0.0.0.0.13-py3.9.egg/spikingjelly/datasets/shd.py", line 395, in __len__
    return self.length
AttributeError: 'SpikingHeidelbergDigits' object has no attribute 'length'

Thanks!

**Comment by fangwei123456** [comment]
Hi, thanks for report this bug. Now I have fixed it. You can try to update by `git pull` and re-install SpikingJelly by `python setup.py install`.

**Comment by negishubham** [comment]
Hi, 

I have another question that is related to SpikingHeidelbergDigitsdataset. So as far as I know this dataset has recordings ranging from 0.24s to 1.17s so how long recordings do you take? Because we would use batching and we would like all recordings to be of the same length in the batch. Is there a parameter in the dataloader that I can change to set the length for the recordings?

Thanks

**Comment by fangwei123456** [comment]
> how long recordings do you take?

It depends on which integration method you use.

> we would like all recordings to be of the same length in the batch

If you want to use frames with each frame having idential duration (e.g., 0.1s), which will cause different frame number for different samples, then you can use pad function provided by spikingjelly. Here is an example:

https://spikingjelly.readthedocs.io/zh_CN/latest/activation_based_en/neuromorphic_datasets.html#fixed-duration-integrating

If you just want to integrate events to frames with idential frame number and ignore the duration, refer to this:

https://spikingjelly.readthedocs.io/zh_CN/latest/activation_based_en/neuromorphic_datasets.html#get-frames-data

**Comment by AllenYolk** [comment]
✅ 已修复。`self.length` 未定义的 bug 已经在 master 中修复。直接 `git pull` 并重新安装即可：

```shell
git pull
pip install -e .
```

之后 `SpikingHeidelbergDigits` 的 dataloader 可以正常工作。

至于你后续问到的"应取多长 recording"——这取决于你想用哪种事件积分方式：

- **按帧数积分（`frames_number`）**：固定帧数（例如 100 帧 / sample），所有样本时间窗长度一致，适合 batch 训练；
- **按时间积分（`duration`）**：固定时间窗口（例如 1s），帧数随样本变化，需要 padding 或 sort by length。

SHD / SSC 这类语音数据集常用 `frames_number` 控制，确保 batch 内 shape 一致。

**Comment by AllenYolk** [comment]
✅ Fixed. The `self.length` undefined bug has been fixed in master. Just `git pull` and reinstall:

```shell
git pull
pip install -e .
```

`SpikingHeidelbergDigits` dataloader now works as expected.

On your follow-up question about how long recordings to use — that depends on the integration method:

- **Frame-based integration (`frames_number`)**: fixed frame count per sample (e.g. 100 frames / sample), uniform length across the dataset, good for batched training.
- **Time-based integration (`duration`)**: fixed time window (e.g. 1s), variable frame count, needs padding or `sort_by_length`.

For SHD / SSC-like speech datasets, `frames_number` is usually used so the batch shapes line up.
