### ISSUE TITLE
speechcommands reproducation

### ISSUE THREAD

**Issue by Hjwinging** [fangwei123456/spikingjelly#330]
Hello, I would like to ask a problem.When I use Spikingjelly to reproduce the code of speechcommands.py, there is a problem, and the audio fails to be read. I have tried many methods and can’t find how to solve the problem.

Traceback (most recent call last):
  File "D:\OneDrive - ilil\pythonProject\spikingjellyTeamExperiments\Voice_classification.py", line 359, in <module>
    for audios, labels in tqdm(train_dataloader):
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\tqdm\std.py", line 1195, in __iter__
    for obj in iterable:
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 530, in __next__
    data = self._next_data()
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 570, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\OneDrive - ilil\pythonProject\spikingjelly\datasets\speechcommands.py", line 188, in __getitem__
    waveform, sample_rate = torchaudio.load(noisepath)
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\torchaudio\backend\soundfile_backend.py", line 197, in load
    with soundfile.SoundFile(filepath, "r") as file_:
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\soundfile.py", line 655, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\soundfile.py", line 1213, in _open
    raise LibsndfileError(err, prefix="Error opening {0!r}: ".format(self.name))
soundfile.LibsndfileError: Error opening './SpeechCommands\\speech_commands_v0.01\\SpeechCommands\\speech_commands_v0.01\\_background_noise_\\doing_the_dishes.wav': System error.

**Comment by Yanqi-Chen** [comment]
It seems to be caused by a corrupted audio file. Have you ever tried to re-download the dataset?

**Comment by Hjwinging** [comment]
Thank you for your help, however, I tried re-downloading the dataset. Because the dataset can be downloaded from the code, right？But I think it may be a problem with the path. I see that there are two SpeechCommands\speech_commands_v0.01 in the error message path, but I can’t find where there is a statement path that controls the search for audio.

**Comment by Yanqi-Chen** [comment]
I have fixed it in the newest commit. Please let me know if you have further questions.

**Comment by Hjwinging** [comment]
My problem has finally been solved, the program can run, and each epoch has output, such as matrix and correct rate, etc. Thank you very much, Mr. Chen.
