### ISSUE TITLE
cifar10dvs数据集无法加载

### ISSUE THREAD

**Issue by Leo-Rosemary** [fangwei123456/spikingjelly#370]
**Issue type**

- [ ] Bug Report
- [ ] Feature Request
- [x] Help wanted
- [ ] Other

**SpikingJelly version**

`0.0.0.0.12`

**Description**
你好，我手动下载了cifar10-dvs数据集，分别为airplane.zip、automobile.zip、bird.zip、cat.zip、deer.zip、dog.zip、frog.zip、horse.zip、truck.zip、ship.zip，并且保存在download文件夹下。之后使用CIFAR10DVS加载该数据集，将.aedat文件转换成.npz文件时，输出提示已经开始转换，但在对应的文件夹下不存在对应的文件，最后也无法成功加载。

Start to convert [D:/Dataset/cifar10dvs/extract\truck\cifar10_truck_990.aedat] to [D:/Dataset/cifar10dvs/events_np\truck\cifar10_truck_990.npz].
Start to convert [D:/Dataset/cifar10dvs/extract\truck\cifar10_truck_991.aedat] to [D:/Dataset/cifar10dvs/events_np\truck\cifar10_truck_991.npz].
Start to convert [D:/Dataset/cifar10dvs/extract\truck\cifar10_truck_992.aedat] to [D:/Dataset/cifar10dvs/events_np\truck\cifar10_truck_992.npz].
Start to convert [D:/Dataset/cifar10dvs/extract\truck\cifar10_truck_993.aedat] to [D:/Dataset/cifar10dvs/events_np\truck\cifar10_truck_993.npz].
Start to convert [D:/Dataset/cifar10dvs/extract\truck\cifar10_truck_994.aedat] to [D:/Dataset/cifar10dvs/events_np\truck\cifar10_truck_994.npz].
Start to convert [D:/Dataset/cifar10dvs/extract\truck\cifar10_truck_995.aedat] to [D:/Dataset/cifar10dvs/events_np\truck\cifar10_truck_995.npz].
Start to convert [D:/Dataset/cifar10dvs/extract\truck\cifar10_truck_996.aedat] to [D:/Dataset/cifar10dvs/events_np\truck\cifar10_truck_996.npz].
Start to convert [D:/Dataset/cifar10dvs/extract\truck\cifar10_truck_997.aedat] to [D:/Dataset/cifar10dvs/events_np\truck\cifar10_truck_997.npz].
Start to convert [D:/Dataset/cifar10dvs/extract\truck\cifar10_truck_998.aedat] to [D:/Dataset/cifar10dvs/events_np\truck\cifar10_truck_998.npz].
Start to convert [D:/Dataset/cifar10dvs/extract\truck\cifar10_truck_999.aedat] to [D:/Dataset/cifar10dvs/events_np\truck\cifar10_truck_999.npz].
Used time = [185.36s].
Mkdir [D:/Dataset/cifar10dvs/frames_number_16_split_by_number].
Mkdir [D:/Dataset/cifar10dvs/frames_number_16_split_by_number\airplane].
Mkdir [D:/Dataset/cifar10dvs/frames_number_16_split_by_number\automobile].
Mkdir [D:/Dataset/cifar10dvs/frames_number_16_split_by_number\bird].
Mkdir [D:/Dataset/cifar10dvs/frames_number_16_split_by_number\cat].
Mkdir [D:/Dataset/cifar10dvs/frames_number_16_split_by_number\deer].
Mkdir [D:/Dataset/cifar10dvs/frames_number_16_split_by_number\dog].
Mkdir [D:/Dataset/cifar10dvs/frames_number_16_split_by_number\frog].
Mkdir [D:/Dataset/cifar10dvs/frames_number_16_split_by_number\horse].
Mkdir [D:/Dataset/cifar10dvs/frames_number_16_split_by_number\ship].
Mkdir [D:/Dataset/cifar10dvs/frames_number_16_split_by_number\truck].
Start ThreadPoolExecutor with max workers = [16].
Used time = [0.0s].
Traceback (most recent call last):
  File "cifar10.py", line 8, in <module>
    origin_set = cifar10_dvs.CIFAR10DVS(root=dataset_dir, data_type='frame', frames_number=T, split_by='number')
  File "C:\Users\10418\.conda\envs\spikformer\lib\site-packages\spikingjelly\datasets\cifar10_dvs.py", line 128, in __init__
    super().__init__(root, None, data_type, frames_number, split_by, duration, custom_integrate_function, custom_integrated_frames_dir_name, transform,
  File "C:\Users\10418\.conda\envs\spikformer\lib\site-packages\spikingjelly\datasets\__init__.py", line 833, in __init__
    super().__init__(root=_root, loader=_loader, extensions=('.npz', ), transform=_transform,
  File "C:\Users\10418\.conda\envs\spikformer\lib\site-packages\torchvision\datasets\folder.py", line 146, in __init__
    samples = self.make_dataset(self.root, class_to_idx, extensions, is_valid_file)
  File "C:\Users\10418\.conda\envs\spikformer\lib\site-packages\torchvision\datasets\folder.py", line 192, in make_dataset
    return make_dataset(directory, class_to_idx, extensions=extensions, is_valid_file=is_valid_file)
  File "C:\Users\10418\.conda\envs\spikformer\lib\site-packages\torchvision\datasets\folder.py", line 102, in make_dataset
    raise FileNotFoundError(msg)
FileNotFoundError: Found no valid file for the classes airplane, automobile, bird, cat, deer, dog, frog, horse, ship, truck. Supported extensions are: .npz

**Minimal code to reproduce the error/bug**

```python
from spikingjelly.clock_driven import functional
from spikingjelly.datasets import cifar10_dvs

dataset_dir = "D:/Dataset/cifar10dvs/"
T=16
origin_set = cifar10_dvs.CIFAR10DVS(root=dataset_dir, data_type='frame', frames_number=T, split_by='number')
```

**Comment by fangwei123456** [comment]
把除了`download`以外的其他文件夹都删除试试

**Comment by Leo-Rosemary** [comment]
还是不行，跟之前报的错一样

**Comment by fangwei123456** [comment]
从github下载012版本的框架，然后把下面这一行
https://github.com/fangwei123456/spikingjelly/blob/1171f5249a4ebeace6ab8d6a74d85579fafb93ed/spikingjelly/datasets/cifar10_dvs.py#L239

注释掉，替换成

`CIFAR10DVS.read_aedat_save_to_np(source_file, target_file)`

然后重新安装框架，再看一下出错的信息。猜测是原来的多线程出错了，而线程池里面的报错信息不会输出

**Comment by Leo-Rosemary** [comment]
你好，代码替换完并且重新安装后，现在的报错信息增加了这些：
Mkdir [D:/Dataset/cifar10dvs/events_np].
Start to convert the origin data from [D:/Dataset/cifar10dvs/extract] to [D:/Dataset/cifar10dvs/events_np] in np.ndarray format.
Mkdir [D:/Dataset/cifar10dvs/events_np\airplane].
Start to convert [D:/Dataset/cifar10dvs/extract\airplane\cifar10_airplane_0.aedat] to [D:/Dataset/cifar10dvs/events_np\airplane\cifar10_airplane_0.npz].
C:\Users\10418\.conda\envs\spikformer\lib\site-packages\spikingjelly-0.0.0.0.12-py3.8.egg\spikingjelly\datasets\cifar10_dvs.py:86: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.

**Comment by fangwei123456** [comment]
numpy版本太老，升级到支持bool数据类型的试试

**Comment by fangwei123456** [comment]
或者把`polarity = read_bits(addr, polarity_mask, polarity_shift).astype(np.bool)`中的`np.bool`改成`bool`试一下

**Comment by Leo-Rosemary** [comment]
按照后一种方式修改了，目前能正常运行，非常感谢！

**Comment by annosoo** [comment]
目前为止的最新版本0.0.0.0.14，这个Bug仍然存在

**Comment by himanshu9084** [comment]
Getting the same error for CIFAR10 DVS, spiking jelly version : 0.0.0.0.14. 
origin_set = CIFAR10DVS(root=data_dir, data_type='frame', frames_number=20, split_by='number')

I tried changing the code as suggested in sub_threads.append(tpe(... with CIFAR10DVS.read_aedat_save_to_np(source_file, target_file) but still getting the same error. 
How can I resolve this ? Thank you. @fangwei123456

**Comment by fangwei123456** [comment]
Hi, you can try to install the latest version from github (not pip). This bug was fixed before. @himanshu9084

**Comment by himanshu9084** [comment]
Thank you, it's working now.
