### ISSUE TITLE
ANN2SNN Example Bug

### ISSUE THREAD

**Issue by fangwei123456** [fangwei123456/spikingjelly#67]
@DingJianhao 
```

python spikingjelly/clock_driven/ann2snn/examples/resnet18_cifar10.py
/home/wangxiao/anaconda3/envs/spikingjelly/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/wangxiao/anaconda3/envs/spikingjelly/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/wangxiao/anaconda3/envs/spikingjelly/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/wangxiao/anaconda3/envs/spikingjelly/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/wangxiao/anaconda3/envs/spikingjelly/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/wangxiao/anaconda3/envs/spikingjelly/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Downloading ./SJ-cifar10-resnet18_model-sample.pth from https://ndownloader.figshare.com/files/26676110, please wait...
输入运行的设备，例如“cpu”或“cuda:0”
 input training device, e.g., "cpu" or "cuda:0": cuda:0
输入分析模型的设备，例如“cpu”或“cuda:0”
 input parsing device, e.g., "cpu" or "cuda:0": cuda:0
输入保存cifar10数据集的位置，例如“./”
 input root directory for saving cifar10 dataset, e.g., "./": ./
输入batch_size，例如“128”
 input batch_size, e.g., "128": 128
输入仿真时长，例如“400”
 input simulating steps, e.g., "400": 400
输入模型名字，例如“resnet18_cifar10”
 input model name, for log_dir generating , e.g., "resnet18_cifar10":
Downloading https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz to ./cifar-10-python.tar.gz
100%|███████████████████████████████████████████████████████████████████████████████████████████▉| 170483712/170498071 [00:29<00:00, 8585486.03it/s]Extracting ./cifar-10-python.tar.gz to ./
170500096it [00:30, 5665526.36it/s]                                                                                                                 
Files already downloaded and verified
use 128 imgs to parse
parser log_dir: ./resnet18_cifar10/parser

Absorbing BatchNorm Parameters...

42it [00:00, 1065.84it/s]
Finish layer reduction!

Getting intermediate output statistics...

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:08<00:00,  5.66it/s]
Finished getting intermediate output statistics!

Normalizing model...

  0%|                                                                                                                        | 0/50 [00:00<?, ?it/s]{'shape': (128, 3, 32, 32), 'min': -2.4290657, 'max': 2.7537065, '99.9': 2.753706455230713}
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:00<00:00, 880.18it/s]
Making new scale node...
Finished normalizing model!
no user-defined conversion method found, use default
Traceback (most recent call last):
  File "spikingjelly/clock_driven/ann2snn/examples/resnet18_cifar10.py", line 110, in <module>
    main('./resnet18_cifar10')
  File "spikingjelly/clock_driven/ann2snn/examples/resnet18_cifar10.py", line 91, in main
    snn = onnxparser.parse(ann, norm_data.to(parser_device))
  File "/home/wangxiao/Documents/vidar-siamfc-pytorch/spikingjelly/spikingjelly/clock_driven/ann2snn/__init__.py", line 108, in parse
    torch.save(model, self.ann_filename)
  File "/home/wangxiao/anaconda3/envs/spikingjelly/lib/python3.7/site-packages/torch/serialization.py", line 370, in save
    _legacy_save(obj, opened_file, pickle_module, pickle_protocol)
  File "/home/wangxiao/anaconda3/envs/spikingjelly/lib/python3.7/site-packages/torch/serialization.py", line 443, in _legacy_save
    pickler.dump(obj)
_pickle.PickleError: can't pickle repeated message fields, convert to list first
(spikingjelly) wangxiao@wx:~/Documents/vidar-siamfc-pytorch/spikingjelly$
```

**Comment by fangwei123456** [comment]
这里不应该是%d
https://github.com/fangwei123456/spikingjelly/blob/542a06430992780c4a18d6c998e5a10445e968d2/spikingjelly/clock_driven/ann2snn/examples/cnn_mnist.py#L113

https://github.com/fangwei123456/spikingjelly/blob/542a06430992780c4a18d6c998e5a10445e968d2/spikingjelly/clock_driven/ann2snn/examples/cnn_fashionmnist.py#L78

**Comment by Yanqi-Chen** [comment]
看起来C/C++的写法带过来了，正常🤣

**Comment by DingJianhao** [comment]
> 看起来C/C++的写法带过来了，正常🤣

我已经很久没写c++了😂

**Comment by wangxiao5791509** [comment]
@DingJianhao  嗨，豪哥，麻烦更新下 ANN2SNN 转换的 example code，目前模型保存那里有 bug，存不下来。

**Comment by DingJianhao** [comment]
@wangxiao5791509 刚刚稍微调整了一下 不过我在win上运行还没遇到过您展示的bug hhh

**Comment by wangxiao5791509** [comment]
I find this code can be modified into: 
[savebug](https://github.com/fangwei123456/spikingjelly/blob/becd57c93ae5f58c52b305b17305c208a8e103a5/spikingjelly/clock_driven/ann2snn/examples/cnn_mnist.py#L198)

torch.save(snn, os.path.join(log_dir,'snn-'+model_name+'.pkl'))    

==>> torch.save(snn.state_dict(), model_weight_savePath+'/snn_model_weights.pth') 


![Screenshot from 2021-04-21 15-49-40](https://user-images.githubusercontent.com/12805786/115516987-424e2880-a2b9-11eb-8725-665f4bc5a82d.png)

**Comment by DingJianhao** [comment]
_pickle.PickleError: can't pickle repeated message fields, convert to list first

这里问题在于pickle没法保存一个op_tree (dict类型)。于是用json转成字符串存下来了！

**Comment by nothingFan** [comment]
运行 example： resnet18_cifar10.py

找不到预训练权值。
![image](https://user-images.githubusercontent.com/44595229/132834259-72cbcc78-5fdb-4547-9957-e93bbed6d32f.png)

**Comment by fangwei123456** [comment]
完整的报错信息？

**Comment by 201528014227051** [comment]
> orch.save(snn.state_dict(), model_weight_savePath+'/snn_model_weights.pth')

感谢方案，保存行得通，有个问题请教一下，但如果采用的是转化的方法的话，这样保存之后只有权重没有模型，在加载的时候，如何获得转化后的模型类的对象呢？ @wangxiao5791509

**Comment by fangwei123456** [comment]
模型是无法保存的，必须有原始python代码才行。

**Comment by 201528014227051** [comment]
> 模型是无法保存的，必须有原始python代码才行。

感谢回复，这就很尴尬了

**Comment by 201528014227051** [comment]
> _pickle.PickleError: can't pickle repeated message fields, convert to list first
> 
> 这里问题在于pickle没法保存一个op_tree (dict类型)。于是用json转成字符串存下来了！

您好，我尝试使用json的格式来保存这个转化后的模型：
`with open(path,'w') as fp:
    json.dump(snn, fp)    
`
报错：Object of type _pt_model is not JSON serializable
修改后
`json.dump(snn, fp)`
还是报错：
Object of type ModuleList is not JSON serializable

不知道这里对您这个转化成json字符串保存，是不是又哪里理解偏差了？

**Comment by fangwei123456** [comment]
@DingJianhao 有时间看一下
