### ISSUE TITLE
CIFAR10-DVS是没有train这个属性吗，是调用同样的函数直接将其分成训练集和测试集吗？

### ISSUE THREAD

**Issue by BugCodeHub** [fangwei123456/spikingjelly#97]

**Comment by fangwei123456** [comment]
是的，用新版框架中的这个函数

https://github.com/fangwei123456/spikingjelly/blob/199b3ad1e6537508207b5c5b4f364775a2ac8a62/spikingjelly/datasets/__init__.py#L421

**Comment by BugCodeHub** [comment]
好的

**Comment by BugCodeHub** [comment]
这个是原始数据集是处理后的吧 origin_dataset: torch.utils.data.Dataset。我这边对这个处理后的数据进行划分出现该问题
Traceback (most recent call last):
  File "/home/a401/.conda/envs/pytorch36/lib/python3.6/site-packages/numpy/lib/npyio.py", line 447, in load
    return pickle.load(fid, **pickle_kwargs)
EOFError: Ran out of input

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/a401/code/train_model/cifar10_DVS_train.py", line 93, in <module>
    train_data_loader = split_to_train_test_set(train_ratio=0.9,origin_dataset=dataset,num_classes=10, random_split=True)
  File "/home/a401/.conda/envs/pytorch36/lib/python3.6/site-packages/spikingjelly-0.0.0.0.7-py3.6.egg/spikingjelly/datasets/__init__.py", line 441, in split_to_train_test_set
  File "/home/a401/.conda/envs/pytorch36/lib/python3.6/site-packages/torchvision/datasets/folder.py", line 137, in __getitem__
    sample = self.loader(path)
  File "/home/a401/.conda/envs/pytorch36/lib/python3.6/site-packages/spikingjelly-0.0.0.0.7-py3.6.egg/spikingjelly/datasets/__init__.py", line 161, in load_npz_frames
  File "/home/a401/.conda/envs/pytorch36/lib/python3.6/site-packages/numpy/lib/npyio.py", line 450, in load
    "Failed to interpret file %s as a pickle" % repr(file))
OSError: Failed to interpret file '/home/a401/code/train_model/cifar10DVS_models/datasets/frames_number_20_split_by_number/bird/cifar10_bird_128.npz' as a pickle

**Comment by fangwei123456** [comment]
用新框架重新生成数据集试试

**Comment by BugCodeHub** [comment]
有把之前旧框架的数据集删了，重新下载和数据处理完了，还是会报错。（CIFAR10-DVS数据集好大，内存占满了，这个有没有办法压缩一些掉，或者可以只处理部分数据集吗）

**Comment by fangwei123456** [comment]
可以，在程序自动解压后，可以删除每个类别里面的多数样本，只保留一两个，用来测试代码能否运行
![image](https://user-images.githubusercontent.com/38352109/128338960-8d18e511-c686-418b-b698-767515ea0042.png)

**Comment by fangwei123456** [comment]
数据集的处理是分步进行的，保留download和extract文件夹，删除其他的文件夹，这样运行的时候应该会从生成event数据开始

**Comment by BugCodeHub** [comment]
嗯嗯，前面我可能因为数据量太大，没执行完就中断，后面再执行一次就报错了。现在我把数据量变小就可以顺利执行。但是还有一个问题，执行到train_data_load赋值的时候会报错，加items()字段好像没这个属性
![image](https://user-images.githubusercontent.com/33653847/128342501-66ac35b8-a1ef-4ca7-a822-a683bd95e3c0.png)。

这个函数返回的是两个数据集吗
![image](https://user-images.githubusercontent.com/33653847/128342937-f8e6b32c-5f14-4d80-8c52-6fed085d4e19.png)

**Comment by BugCodeHub** [comment]
如果直接从train_data_loader取出img和label可以吗
